# Site settings
title: The Long and Winding Code
header-img: img/home-bg.png
email: samantha.marie.garcia@gmail.com
copyright_name: SamanthaMGarcia
description: > # this means to ignore newlines until "baseurl:"
  My journey to becoming a full stack web developer. 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  SamanthaMGarcia
learn_profile: SamanthaMGarcia
email_username: samantha.marie.garcia@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
